apiVersion: v1
kind: PersistentVolume
metadata:
  name: gateway-shared-synapse-configs-volume
  namespace: wso2
  labels:
    aws-availability-zone: us-east-1
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: fs-8f679af7.efs.us-east-2.amazonaws.com
    path: /