apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: wso2apim
  namespace: wso2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wso2apim
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 85