apiVersion: v1
kind: PersistentVolume
metadata:
  name: gateway-shared-synapse-configs-volume
  namespace: wso2
  labels:
    aws-availability-zone: us-east-1
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"