apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gateway-shared-synapse-configs-volume-claim
  namespace: wso2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  selector:
    matchLabels:
      aws-availability-zone: us-east-1